INSERT INTO job_applied
            (job_id,
             application_sent_date,
             custom_resume,
             resume_file_name,
             cover_letter_sent,
             cover_letter_file_name,
             status)
VALUES      (1,
             '2024-02-01',
             True,
             'resume_01.pdf',
             True,
             'cover_letter_01.pdf',
             'Submitted'),
            (2,
             '2024-02-02',
             False,
             'resume_02.pdf',
             False,
             NULL,
             'Interview Scheduled'),
            (3,
             '2024-02-03',
             True,
             'resume_03.pdf',
             True,
             'cover_letter_03.pdf',
             'ghosted'),
            (4,
             '2024-02-04',
             True,
             'resume_04.pdf',
             False,
             NULL,
             'Submitted'),
            (5,
             '2024-02-05',
             False,
             'resume_05.pdf',
             True,
             'cover_letter_05.pdf',
             'Rejected');

SELECT *
FROM job_applied;